# Want to have some property like 
# auth = { type="auth_type", some data }
simple_auth = [
    { id = "boss", key = "BossKEY", from_env = false, roles = [
        "ADMIN",
        "MANAGER",
    ] },
    { id = "manager", key = "ManagerKEY", from_env = false, roles = [
        "MANAGER",
    ] },
    { id = "user", key = "UserKEY", from_env = false },
]

[[storage]]
# id = "default"
type = "sqlite"
# file = "./db.sqlite3"
# file = "../db.sqlite3"
file = ""
create_db = true
wal = true
migrations_dir = "sqlite/migrations"
