[[endpoint]]
uri = "/payments/list"
fetch_limit = 20

[endpoint.resource]
type = "query"
query = "SELECT * FROM payments LIMIT {{-limit-}} OFFSET {{-offset-}}"

[[endpoint]]
uri = "/payment/{payment_id:\\d+}/revalidate"
single_record_response = true

[[endpoint.pre_processors]]
type = "simple_authentication"

[[endpoint.pre_processors]]
type = "authorize"
rules = "#boss OR (ADMIN AND MANAGER)"

[endpoint.resource]
type = "query_script_lua"
script = """

-- Just reusing existing input context where 'payment_id' argument exists.
local allowed = storage_query_value(
    "SELECT COALESCE(reprocess_trigger <= datetime('now', '-20 seconds'), 1) FROM payments WHERE id = {{payment_id}}",
    ctx:load_input()
);

-- And now we could conditionally stop further processing
-- NOTE: sqlite returns integer instead boolean and it is not auto converted in Lua
if allowed ~= 1 then
    error_input("Can't trigger reprocessing more than once in a 20 seconds");
end

-- Returning the query to be executed by endpoint handler.
return "UPDATE payments SET reprocess_trigger = current_timestamp WHERE id = {{payment_id}} RETURNING id, reprocess_trigger";
"""
